"""Generate Vivado bridge artifacts for FPGAI HLS outputs.

Vivado bridge intentionally separates script generation from full hardware
implementation. It creates reproducible Tcl scripts for:

* exporting an existing Vitis HLS project as Vivado IP;
* creating a Vivado project and block-design skeleton;
* running synthesis/implementation/report commands when explicitly enabled;
* extracting report/artifact metadata later.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from .boards import get_board


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _find_hls_dir(build_dir: Path) -> Optional[Path]:
    for cand in [build_dir / "hls", build_dir / "HLS"]:
        if cand.exists():
            return cand
    matches = list(build_dir.glob("**/run_hls.tcl"))
    if matches:
        return matches[0].parent
    return None


def _top_name_from_manifest(manifest: Dict[str, Any]) -> str:
    for key in ("top_name", "top", "hls_top", "kernel_name"):
        val = manifest.get(key)
        if isinstance(val, str) and val:
            return val
    hls = manifest.get("hls") if isinstance(manifest.get("hls"), dict) else {}
    for key in ("top_name", "top", "hls_top", "kernel_name"):
        val = hls.get(key)
        if isinstance(val, str) and val:
            return val
    return "deeplearn"


def _load_json(path: Path) -> Dict[str, Any]:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}


def _hls_export_tcl(hls_dir: Path, out_dir: Path, top_name: str, part: str) -> str:
    # Keep paths Tcl-normalized and relative to script location where possible.
    return rf'''# Auto-generated by FPGAI Vivado bridge.
# Export the existing Vitis HLS solution as Vivado IP.
set script_dir [file normalize [file dirname [info script]]]
set hls_dir [file normalize "{hls_dir.as_posix()}"]
set export_dir [file normalize "{(out_dir / 'hls_ip').as_posix()}"]
file mkdir $export_dir
# Important: existing HLS projects contain relative source paths such as ./src/deeplearn.cpp.
# Vitis HLS must run from the HLS build directory before csynth/export.
cd $hls_dir

puts "FPGAI-Vivado HLS dir: $hls_dir"
puts "FPGAI-Vivado Export dir: $export_dir"

set proj_dir [file join $hls_dir fpgai_hls_proj]
if {{![file exists $proj_dir]}} {{
  error "Cannot find Vitis HLS project: $proj_dir"
}}

open_project $proj_dir
open_solution sol1
# Force the HLS solution part to match the Vivado target board. This avoids
# exporting IP metadata that Vivado later rejects as unsupported for the
# selected FPGA part.
set_part "{part}"
puts "FPGAI-Vivado HLS export part: {part}"
# csynth_design is intentionally run here so exported IP is based on synthesized RTL.
csynth_design
config_export -format ip_catalog -rtl verilog
export_design -format ip_catalog -rtl verilog -output $export_dir
# Mirror the canonical HLS packaged-IP directory into vivado_bridge/hls_ip so
# downstream Vivado scripts and artifact extraction have one stable IP repo path.
set impl_ip_dir [file join $proj_dir sol1 impl ip]
if {{[file exists $impl_ip_dir]}} {{
  puts "FPGAI-Vivado Mirroring packaged IP from $impl_ip_dir to $export_dir"
  catch {{file copy -force $impl_ip_dir $export_dir}} copy_msg
  puts "FPGAI-Vivado IP mirror result: $copy_msg"
}}
puts "FPGAI-Vivado HLS IP export finished for top={top_name}"
exit
'''


def _bd_common_helpers() -> str:
    return """proc fpgai_first_intf {cell patterns} {
  foreach pat $patterns {
    set hits [get_bd_intf_pins -quiet "$cell/$pat"]
    if {[llength $hits] > 0} { return [lindex $hits 0] }
  }
  set allpins [get_bd_intf_pins -quiet "$cell/*"]
  foreach pat $patterns {
    foreach pin $allpins {
      set short [lindex [split $pin /] end]
      if {[string match -nocase $pat $short]} { return $pin }
    }
  }
  return ""
}

proc fpgai_first_pin {cell patterns} {
  foreach pat $patterns {
    set hits [get_bd_pins -quiet "$cell/$pat"]
    if {[llength $hits] > 0} { return [lindex $hits 0] }
  }
  set allpins [get_bd_pins -quiet "$cell/*"]
  foreach pat $patterns {
    foreach pin $allpins {
      set short [lindex [split $pin /] end]
      if {[string match -nocase $pat $short]} { return $pin }
    }
  }
  return ""
}

proc fpgai_connect_intf_required {src dst label} {
  if {$src eq "" || $dst eq ""} {
    error "FPGAI-Vivado missing interface for $label: src=$src dst=$dst"
  }
  puts "FPGAI-Vivado connect $label: $src -> $dst"
  connect_bd_intf_net $src $dst
}

proc fpgai_connect_pin_if_exists {src dst label} {
  if {$src ne "" && $dst ne ""} {
    set existing [get_bd_nets -quiet -of_objects $dst]
    if {[llength $existing] > 0} {
      puts "FPGAI-Vivado skip already-connected pin $label: dst=$dst net=$existing"
      return
    }
    puts "FPGAI-Vivado connect $label: $src -> $dst"
    connect_bd_net $src $dst
  } else {
    puts "FPGAI-Vivado skip optional pin $label: src=$src dst=$dst"
  }
}

proc fpgai_connect_net_if_unconnected {src dst label} {
  if {$src eq "" || $dst eq ""} {
    puts "FPGAI-Vivado skip net $label: src=$src dst=$dst"
    return
  }
  set existing [get_bd_nets -quiet -of_objects $dst]
  if {[llength $existing] > 0} {
    puts "FPGAI-Vivado skip already-connected net $label: dst=$dst net=$existing"
    return
  }
  puts "FPGAI-Vivado connect net $label: $src -> $dst"
  connect_bd_net $src $dst
}
"""


def _bd_accelerator_tcl(top_name: str) -> str:
    return f"""set hls_top_name "{top_name}"
set hls_ip_defs [get_ipdefs -all "*$hls_top_name*"]
puts "FPGAI-Vivado Candidate HLS IP defs for $hls_top_name: $hls_ip_defs"
if {{[llength $hls_ip_defs] == 0}} {{
  puts "FPGAI-Vivado Available HLS-like IP defs: [get_ipdefs -all *hls*]"
  error "Could not find exported HLS IP for top=$hls_top_name in current IP catalog"
}}
set hls_vlnv [lindex $hls_ip_defs 0]
puts "FPGAI-Vivado Using HLS IP VLNV: $hls_vlnv"
create_bd_cell -type ip -vlnv $hls_vlnv ${{hls_top_name}}_0
set hls_cell ${{hls_top_name}}_0

set hls_in [fpgai_first_intf $hls_cell {{in_stream in_r s_axis_in_r S_AXIS_IN_R *in_stream* *in_r* *input*}}]
set hls_aux [fpgai_first_intf $hls_cell {{aux aux_stream s_axis_aux S_AXIS_AUX *aux* *target*}}]
set hls_out [fpgai_first_intf $hls_cell {{out_stream out_r m_axis_out_r M_AXIS_OUT_R *out_stream* *out_r* *output*}}]
puts "FPGAI-Vivado HLS stream interfaces: in=$hls_in aux=$hls_aux out=$hls_out"

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma:* axi_dma_0
if {{$hls_aux ne ""}} {{
  create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma:* axi_dma_aux_0
}} else {{
  puts "FPGAI-Vivado no aux AXIS interface detected; skipping auxiliary DMA."
}}
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:* rst_ps_0_100M
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:* axi_ctrl_interconnect
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:* axi_mem_interconnect

catch {{set_property -dict [list CONFIG.c_include_sg {{0}} CONFIG.c_include_mm2s {{1}} CONFIG.c_include_s2mm {{1}}] [get_bd_cells axi_dma_0]}} dma0_cfg_msg
if {{$hls_aux ne ""}} {{
  catch {{set_property -dict [list CONFIG.c_include_sg {{0}} CONFIG.c_include_mm2s {{1}} CONFIG.c_include_s2mm {{0}}] [get_bd_cells axi_dma_aux_0]}} dmaaux_cfg_msg
}} else {{
  set dmaaux_cfg_msg "skipped: no aux AXIS interface"
}}
puts "FPGAI-Vivado DMA0 config result: $dma0_cfg_msg"
puts "FPGAI-Vivado DMA aux config result: $dmaaux_cfg_msg"

set ctrl_mi_count [expr {{$hls_aux ne "" ? 3 : 2}}]
set mem_si_count [expr {{$hls_aux ne "" ? 3 : 2}}]
set_property -dict [list CONFIG.NUM_SI {{1}} CONFIG.NUM_MI $ctrl_mi_count] [get_bd_cells axi_ctrl_interconnect]
set_property -dict [list CONFIG.NUM_SI $mem_si_count CONFIG.NUM_MI {{1}}] [get_bd_cells axi_mem_interconnect]

connect_bd_net $clk [get_bd_pins rst_ps_0_100M/slowest_sync_clk]
connect_bd_net $rstn [get_bd_pins rst_ps_0_100M/ext_reset_in]
set periph_aresetn [get_bd_pins rst_ps_0_100M/peripheral_aresetn]

set aux_clk_pins {{}}
if {{$hls_aux ne ""}} {{
  set aux_clk_pins [get_bd_pins -quiet axi_dma_aux_0/*aclk]
}}
foreach pin [concat \\
  [get_bd_pins -quiet axi_dma_0/*aclk] \\
  $aux_clk_pins \\
  [get_bd_pins -quiet axi_ctrl_interconnect/*ACLK] \\
  [get_bd_pins -quiet axi_mem_interconnect/*ACLK] \\
  [list [fpgai_first_pin $hls_cell {{ap_clk aclk ACLK}}]] \\
] {{
  if {{$pin ne ""}} {{ fpgai_connect_net_if_unconnected $clk $pin "accelerator clock fanout" }}
}}
set aux_reset_pins {{}}
if {{$hls_aux ne ""}} {{
  set aux_reset_pins [get_bd_pins -quiet axi_dma_aux_0/*aresetn]
}}
foreach pin [concat \\
  [get_bd_pins -quiet axi_dma_0/*aresetn] \\
  $aux_reset_pins \\
  [get_bd_pins -quiet axi_ctrl_interconnect/*ARESETN] \\
  [get_bd_pins -quiet axi_mem_interconnect/*ARESETN] \\
  [list [fpgai_first_pin $hls_cell {{ap_rst_n aresetn ARESETN}}]] \\
] {{
  if {{$pin ne ""}} {{ fpgai_connect_net_if_unconnected $periph_aresetn $pin "accelerator reset fanout" }}
}}

fpgai_connect_intf_required $ps_ctrl_axi [get_bd_intf_pins axi_ctrl_interconnect/S00_AXI] "PS control master to ctrl interconnect"
set hls_ctrl [fpgai_first_intf $hls_cell {{s_axi_CTRL S_AXI_CTRL CTRL s_axi_control S_AXI_CONTROL *CTRL* *control*}}]
fpgai_connect_intf_required [get_bd_intf_pins axi_ctrl_interconnect/M00_AXI] $hls_ctrl "control to HLS AXI-Lite"
fpgai_connect_intf_required [get_bd_intf_pins axi_ctrl_interconnect/M01_AXI] [get_bd_intf_pins axi_dma_0/S_AXI_LITE] "control to main DMA AXI-Lite"
if {{$hls_aux ne ""}} {{
  fpgai_connect_intf_required [get_bd_intf_pins axi_ctrl_interconnect/M02_AXI] [get_bd_intf_pins axi_dma_aux_0/S_AXI_LITE] "control to aux DMA AXI-Lite"
}} else {{
  puts "FPGAI-Vivado skip aux DMA AXI-Lite connection: no aux AXIS interface"
}}

fpgai_connect_intf_required [get_bd_intf_pins axi_dma_0/M_AXI_MM2S] [get_bd_intf_pins axi_mem_interconnect/S00_AXI] "main DMA MM2S to memory interconnect"
fpgai_connect_intf_required [get_bd_intf_pins axi_dma_0/M_AXI_S2MM] [get_bd_intf_pins axi_mem_interconnect/S01_AXI] "main DMA S2MM to memory interconnect"
if {{$hls_aux ne ""}} {{
  fpgai_connect_intf_required [get_bd_intf_pins axi_dma_aux_0/M_AXI_MM2S] [get_bd_intf_pins axi_mem_interconnect/S02_AXI] "aux DMA MM2S to memory interconnect"
}} else {{
  puts "FPGAI-Vivado skip aux DMA memory connection: no aux AXIS interface"
}}
fpgai_connect_intf_required [get_bd_intf_pins axi_mem_interconnect/M00_AXI] $ps_mem_axi "memory interconnect to PS memory slave"

fpgai_connect_intf_required [get_bd_intf_pins axi_dma_0/M_AXIS_MM2S] $hls_in "main DMA stream to HLS input"
if {{$hls_aux ne ""}} {{
  fpgai_connect_intf_required [get_bd_intf_pins axi_dma_aux_0/M_AXIS_MM2S] $hls_aux "aux DMA stream to HLS aux"
}} else {{
  puts "FPGAI-Vivado skip aux DMA stream connection: no aux AXIS interface"
}}
fpgai_connect_intf_required $hls_out [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM] "HLS output to main DMA stream return"

assign_bd_address
validate_bd_design
save_bd_design
puts "FPGAI-Vivado Full block design validated: $design_name"
"""

def _create_zynq7000_bd_tcl(board_name: str, top_name: str) -> str:
    return f"""# Auto-generated FPGAI full Vivado block design.
# Target: {board_name}, HLS top: {top_name}
# Board family: Zynq-7000 / processing_system7

set design_name fpgai_bd
create_bd_design $design_name

{_bd_common_helpers()}
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:* processing_system7_0
set_property -dict [list \\
  CONFIG.PCW_USE_M_AXI_GP0 {{1}} \\
  CONFIG.PCW_USE_S_AXI_HP0 {{1}} \\
  CONFIG.PCW_EN_CLK0_PORT {{1}} \\
  CONFIG.PCW_EN_RST0_PORT {{1}} \\
  CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {{100}} \\
] [get_bd_cells processing_system7_0]

catch {{apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 -config {{make_external "FIXED_IO, DDR" apply_board_preset "1"}} [get_bd_cells processing_system7_0]}} ps_auto_msg
puts "FPGAI-Vivado PS automation result: $ps_auto_msg"
catch {{make_bd_intf_pins_external [get_bd_intf_pins processing_system7_0/DDR]}} ddr_ext_msg
catch {{make_bd_intf_pins_external [get_bd_intf_pins processing_system7_0/FIXED_IO]}} fixed_ext_msg
puts "FPGAI-Vivado DDR external result: $ddr_ext_msg"
puts "FPGAI-Vivado FIXED_IO external result: $fixed_ext_msg"

set clk [get_bd_pins processing_system7_0/FCLK_CLK0]
set rstn [get_bd_pins processing_system7_0/FCLK_RESET0_N]
set ps_ctrl_axi [get_bd_intf_pins processing_system7_0/M_AXI_GP0]
set ps_mem_axi [get_bd_intf_pins processing_system7_0/S_AXI_HP0]
fpgai_connect_pin_if_exists $clk [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] "PS GP0 clock"
fpgai_connect_pin_if_exists $clk [get_bd_pins processing_system7_0/S_AXI_HP0_ACLK] "PS HP0 clock"

{_bd_accelerator_tcl(top_name)}"""


def _create_zynqmp_bd_tcl(board_name: str, top_name: str) -> str:
    return f"""# Auto-generated FPGAI full Vivado block design.
# Target: {board_name}, HLS top: {top_name}
# Board family: Zynq UltraScale+ MPSoC / zynq_ultra_ps_e

set design_name fpgai_bd
create_bd_design $design_name

{_bd_common_helpers()}
create_bd_cell -type ip -vlnv xilinx.com:ip:zynq_ultra_ps_e:* zynq_ultra_ps_e_0
catch {{apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {{apply_board_preset "1"}} [get_bd_cells zynq_ultra_ps_e_0]}} ps_auto_msg
puts "FPGAI-Vivado ZynqMP PS automation result: $ps_auto_msg"

catch {{set_property -dict [list \\
  CONFIG.PSU__USE__M_AXI_GP0 {{1}} \\
  CONFIG.PSU__USE__S_AXI_GP0 {{1}} \\
  CONFIG.PSU__FPGA_PL0_ENABLE {{1}} \\
  CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {{100}} \\
] [get_bd_cells zynq_ultra_ps_e_0]}} zynqmp_cfg_msg
puts "FPGAI-Vivado ZynqMP config result: $zynqmp_cfg_msg"

catch {{make_bd_intf_pins_external [get_bd_intf_pins zynq_ultra_ps_e_0/DDR]}} ddr_ext_msg
catch {{make_bd_intf_pins_external [get_bd_intf_pins zynq_ultra_ps_e_0/FIXED_IO]}} fixed_ext_msg
puts "FPGAI-Vivado DDR external result: $ddr_ext_msg"
puts "FPGAI-Vivado FIXED_IO external result: $fixed_ext_msg"

set clk [fpgai_first_pin zynq_ultra_ps_e_0 {{pl_clk0 maxihpm0_fpd_aclk saxihpc0_fpd_aclk *pl_clk0*}}]
set rstn [fpgai_first_pin zynq_ultra_ps_e_0 {{pl_resetn0 *resetn*}}]
if {{$clk eq ""}} {{ error "FPGAI-Vivado could not find ZynqMP PL clock pin" }}
if {{$rstn eq ""}} {{
  puts "FPGAI-Vivado ZynqMP reset pin not found; creating active-low reset constant through proc_sys_reset only"
  set rstn $clk
}}

set ps_ctrl_axi [fpgai_first_intf zynq_ultra_ps_e_0 {{M_AXI_HPM0_FPD M_AXI_HPM0_LPD *M_AXI_HPM* *M_AXI_GP*}}]
set ps_mem_axi [fpgai_first_intf zynq_ultra_ps_e_0 {{S_AXI_HPC0_FPD S_AXI_HP0_FPD S_AXI_HPC1_FPD *S_AXI_HPC* *S_AXI_HP*}}]
if {{$ps_ctrl_axi eq ""}} {{ error "FPGAI-Vivado could not find ZynqMP PS AXI master interface" }}
if {{$ps_mem_axi eq ""}} {{ error "FPGAI-Vivado could not find ZynqMP PS AXI memory slave interface" }}

foreach pin [concat \\
  [get_bd_pins -quiet zynq_ultra_ps_e_0/*aclk] \\
  [get_bd_pins -quiet zynq_ultra_ps_e_0/*ACLK] \\
] {{
  if {{$pin ne ""}} {{ fpgai_connect_net_if_unconnected $clk $pin "PS clock fanout" }}
}}

{_bd_accelerator_tcl(top_name)}"""


def _create_bd_tcl(board_name: str, top_name: str, ps_type: str = "processing_system7") -> str:
    if ps_type == "processing_system7":
        return _create_zynq7000_bd_tcl(board_name, top_name)
    if ps_type == "zynq_ultra_ps_e":
        return _create_zynqmp_bd_tcl(board_name, top_name)
    raise ValueError(f"Unsupported Vivado PS type for board {board_name}: {ps_type}")

def _run_vivado_tcl(board: Dict[str, Any], top_name: str, run_impl_default: bool) -> str:
    run_impl = "1" if run_impl_default else "0"
    board_part = board.get("board_part") or ""
    return rf'''# Auto-generated by FPGAI.
# Creates a Vivado project, imports exported HLS IP, runs OOC IP reports, and
# optionally builds a board-specific PS/DMA block design through bitstream/XSA.

set script_dir [file normalize [file dirname [info script]]]
set vivado_dir [file normalize [file join $script_dir ..]]
set project_dir [file normalize [file join $vivado_dir project]]
set report_dir [file normalize [file join $vivado_dir reports]]
set bit_dir [file normalize [file join $vivado_dir bitstream]]
set ip_repo [file normalize [file join $vivado_dir hls_ip]]
file mkdir $project_dir
file mkdir $report_dir
file mkdir $bit_dir

set part "{board['part']}"
set board_part "{board_part}"
set run_impl {run_impl}
if {{[info exists ::env(FPGAI_VIVADO_RUN_IMPL)]}} {{
  set run_impl $::env(FPGAI_VIVADO_RUN_IMPL)
}}
set jobs [expr {{[info exists ::env(FPGAI_VIVADO_JOBS)] ? $::env(FPGAI_VIVADO_JOBS) : 4}}]

puts "FPGAI-Vivado project_dir=$project_dir"
puts "FPGAI-Vivado ip_repo=$ip_repo"
puts "FPGAI-Vivado part=$part board_part=$board_part run_impl=$run_impl"

create_project fpgai_vivado $project_dir -part $part -force
if {{$board_part ne ""}} {{
  catch {{set_property board_part $board_part [current_project]}} board_part_msg
  puts "FPGAI-Vivado board_part result: $board_part_msg"
}}

if {{[file exists $ip_repo]}} {{
  set component_paths [glob -nocomplain -directory $ip_repo -types f component.xml]
  set nested_component_paths [glob -nocomplain -directory $ip_repo -types f */component.xml */*/component.xml */*/*/component.xml]
  set component_paths [concat $component_paths $nested_component_paths]
  foreach component_xml $component_paths {{
    puts "FPGAI-Vivado Normalizing IP compatibility: $component_xml"
    catch {{
      ipx::open_core $component_xml
      set_property supported_families {{zynq Production artix7 Production kintex7 Production zynquplus Production}} [ipx::current_core]
      ipx::save_core [ipx::current_core]
      ipx::unload_core [ipx::current_core]
    }} ipx_msg
    puts "FPGAI-Vivado IP compatibility result: $ipx_msg"
  }}
  set_property ip_repo_paths $ip_repo [current_project]
  update_ip_catalog
}} else {{
  error "FPGAI-Vivado HLS IP repo does not exist: $ip_repo"
}}

set hls_top_name "{top_name}"
set hls_ip_defs [get_ipdefs -all "*$hls_top_name*"]
puts "FPGAI-Vivado Candidate HLS IP defs for $hls_top_name: $hls_ip_defs"
if {{[llength $hls_ip_defs] == 0}} {{
  puts "FPGAI-Vivado Available HLS-like IP defs: [get_ipdefs -all *hls*]"
  error "Could not find exported HLS IP for top=$hls_top_name in current IP catalog"
}}
set hls_vlnv [lindex $hls_ip_defs 0]
puts "FPGAI-Vivado Using HLS IP VLNV: $hls_vlnv"

set ip_inst "${{hls_top_name}}_ip_ooc"
create_ip -vlnv $hls_vlnv -module_name $ip_inst
set ip_obj [get_ips $ip_inst]
generate_target all $ip_obj
synth_ip $ip_obj

set dcp_candidates [glob -nocomplain \
  [file join $project_dir fpgai_vivado.gen sources_1 ip $ip_inst ${{ip_inst}}.dcp] \
  [file join $project_dir fpgai_vivado.gen sources_1 ip * *.dcp] \
  [file join $project_dir *.gen sources_1 ip * *.dcp]]
puts "FPGAI-Vivado OOC DCP candidates: $dcp_candidates"
if {{[llength $dcp_candidates] == 0}} {{
  error "FPGAI-Vivado could not find synthesized OOC DCP for $ip_inst"
}}
set ooc_dcp [lindex $dcp_candidates 0]
puts "FPGAI-Vivado Opening synthesized checkpoint: $ooc_dcp"
open_checkpoint $ooc_dcp
report_utilization -file [file join $report_dir utilization_synth.rpt]
report_timing_summary -file [file join $report_dir timing_synth.rpt]
catch {{report_power -file [file join $report_dir power_synth.rpt]}} power_msg
puts "FPGAI-Vivado report_power result: $power_msg"
close_design

if {{$run_impl}} {{
  puts "FPGAI-Vivado Starting full BD implementation/bitstream path"
  source [file join $script_dir create_bd.tcl]
  set bd_files [get_files -quiet *.bd]
  if {{[llength $bd_files] == 0}} {{
    set bd_files [get_files -quiet $project_dir/fpgai_vivado.srcs/sources_1/bd/*/*.bd]
  }}
  puts "FPGAI-Vivado BD files: $bd_files"
  if {{[llength $bd_files] == 0}} {{ error "No BD file found after create_bd.tcl" }}
  set bd_file [lindex $bd_files 0]
  generate_target all $bd_file
  make_wrapper -files $bd_file -top
  set wrapper_files [glob -nocomplain $project_dir/fpgai_vivado.gen/sources_1/bd/*/hdl/*_wrapper.v]
  puts "FPGAI-Vivado wrapper files: $wrapper_files"
  if {{[llength $wrapper_files] == 0}} {{ error "No generated BD wrapper found" }}
  add_files -norecurse $wrapper_files
  update_compile_order -fileset sources_1

  launch_runs synth_1 -jobs $jobs
  wait_on_run synth_1
  open_run synth_1
  report_utilization -file [file join $report_dir utilization_bd_synth.rpt]
  report_timing_summary -file [file join $report_dir timing_bd_synth.rpt]
  catch {{report_power -file [file join $report_dir power_bd_synth.rpt]}} bd_synth_power_msg
  puts "FPGAI-Vivado BD synth report_power result: $bd_synth_power_msg"

  launch_runs impl_1 -to_step write_bitstream -jobs $jobs
  wait_on_run impl_1
  open_run impl_1
  report_utilization -file [file join $report_dir utilization_impl.rpt]
  report_timing_summary -file [file join $report_dir timing_impl.rpt]
  catch {{report_power -file [file join $report_dir power_impl.rpt]}} impl_power_msg
  puts "FPGAI-Vivado impl report_power result: $impl_power_msg"

  set bit_candidates [glob -nocomplain $project_dir/fpgai_vivado.runs/impl_1/*.bit]
  puts "FPGAI-Vivado bit candidates: $bit_candidates"
  foreach bit_file $bit_candidates {{ file copy -force $bit_file [file join $bit_dir [file tail $bit_file]] }}
  write_hw_platform -fixed -include_bit -force -file [file join $bit_dir fpgai_bd.xsa]
}}

puts "FPGAI-Vivado Vivado flow finished for top={top_name}"
exit
'''

def _readme(board: Dict[str, Any], top_name: str) -> str:
    return f'''# FPGAI Vivado Bridge Artifact

This folder was generated by FPGAI.

## Target

- top: `{top_name}`
- board: `{board['name']}`
- part: `{board['part']}`
- board_part: `{board.get('board_part') or ''}`
- overlay_style: `{board['overlay_style']}`

## Files

- `scripts/export_hls_ip.tcl`: opens the generated Vitis HLS project, runs synthesis, and exports Vivado IP.
- `scripts/create_bd.tcl`: block-design skeleton for the exported HLS IP.
- `scripts/run_vivado.tcl`: creates the Vivado project, imports the IP repo, runs synthesis reports, and optionally implementation/bitstream.
- `vivado_bridge_manifest.json`: machine-readable artifact/configuration metadata.

## Automated command from repo root

```bash
python -m fpgai.backends.vivado.run_bridge <experiment_dir> --board pynq_z2 --export-hls-ip
python -m fpgai.backends.vivado.run_bridge <experiment_dir> --board pynq_z2 --export-hls-ip --run-vivado-synth
python -m fpgai.backends.vivado.run_bridge <experiment_dir> --board pynq_z2 --export-hls-ip --run-vivado-impl
```

The lower-level Tcl scripts remain in this folder for reproducibility and debugging.
'''


def generate_vivado_bridge_for_artifact(
    artifact_dir: str | Path,
    board_name: str = "pynq_z2",
    run_impl_default: bool = False,
) -> Dict[str, Any]:
    artifact = Path(artifact_dir).resolve()
    build_dir = artifact / "build"
    if not build_dir.exists():
        build_dir = artifact
    manifest = _load_json(build_dir / "manifest.json")
    top_name = _top_name_from_manifest(manifest)
    board = get_board(board_name).to_dict()
    hls_dir = _find_hls_dir(build_dir)
    if hls_dir is None:
        raise FileNotFoundError(f"Could not find HLS directory/run_hls.tcl under {build_dir}")

    out_dir = build_dir / "vivado_bridge"
    scripts_dir = out_dir / "scripts"
    reports_dir = out_dir / "reports"
    (out_dir / "hls_ip").mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    _write(scripts_dir / "export_hls_ip.tcl", _hls_export_tcl(hls_dir, out_dir, top_name, board["part"]))
    _write(scripts_dir / "create_bd.tcl", _create_bd_tcl(board["name"], top_name, board.get("ps_type", "processing_system7")))
    _write(scripts_dir / "run_vivado.tcl", _run_vivado_tcl(board, top_name, run_impl_default))
    _write(out_dir / "README_VIVADO.md", _readme(board, top_name))

    artifact = {
        "vivado_bridge_generated": True,
        "vivado_tcl_generated": True,
        "hls_export_tcl_generated": True,
        "vivado_project_tcl_generated": True,
        "block_design_tcl_generated": True,
        "board": board["name"],
        "part": board["part"],
        "board_part": board.get("board_part"),
        "ps_type": board.get("ps_type"),
        "overlay_style": board.get("overlay_style"),
        "supports_bridge_generation": board.get("supports_bridge_generation", True),
        "supports_hls_ip_export": board.get("supports_hls_ip_export", True),
        "supports_vivado_synth": board.get("supports_vivado_synth", True),
        "supports_vivado_impl": board.get("supports_vivado_impl", True),
        "top_name": top_name,
        "artifact_dir": artifact.as_posix(),
        "build_dir": build_dir.as_posix(),
        "hls_dir": hls_dir.as_posix(),
        "vivado_bridge_dir": out_dir.as_posix(),
        "hls_ip_expected": True,
        "hls_ip_exported": False,
        "vivado_synth_requested": True,
        "vivado_impl_requested": bool(run_impl_default),
        "bitstream_requested": bool(run_impl_default),
        "reports_expected": [
            "utilization_synth.rpt",
            "timing_synth.rpt",
            "power_synth.rpt",
            "utilization_impl.rpt",
            "timing_impl.rpt",
            "power_impl.rpt",
        ],
        "energy_estimation": {
            "enabled_after_power_report": True,
            "formula": "estimated_energy_j = vivado_total_power_w * hls_latency_s",
            "status": "pending_reports",
        },
    }
    _write(out_dir / "vivado_bridge_manifest.json", json.dumps(artifact, indent=2, sort_keys=True))
    return artifact


def _iter_artifacts(experiment_dir: Path) -> Iterable[Path]:
    artifacts = experiment_dir / "artifacts"
    if artifacts.exists():
        for p in sorted(artifacts.iterdir()):
            if p.is_dir():
                yield p
    else:
        # Allow direct artifact/build paths for debugging.
        yield experiment_dir


def generate_vivado_bridge_for_experiment(
    experiment_dir: str | Path,
    board_name: str = "pynq_z2",
    run_impl_default: bool = False,
) -> List[Dict[str, Any]]:
    exp = Path(experiment_dir).resolve()
    rows: List[Dict[str, Any]] = []
    for art in _iter_artifacts(exp):
        try:
            ev = generate_vivado_bridge_for_artifact(art, board_name=board_name, run_impl_default=run_impl_default)
            ev["design"] = art.name
            ev["status"] = "generated"
        except Exception as exc:  # keep artifact-driven behavior across all records
            ev = {
                "design": art.name,
                "status": "error",
                "vivado_bridge_generated": False,
                "error": str(exc),
                "artifact_dir": art.as_posix(),
            }
        rows.append(ev)
    out = exp / "vivado_bridge_artifact.json"
    _write(out, json.dumps(rows, indent=2, sort_keys=True))
    return rows
