# Auto-generated by FPGAI external HLS integration
open_project -reset fpgai_external_hls
set_top deeplearn
add_files ./src/deeplearn.cpp -cflags "-I./include -I./external/community_scale_bias_hls/include"
add_files "./external/community_scale_bias_hls/src/000_scale_bias.cpp" -cflags "-I./include -I./external/community_scale_bias_hls/include"
add_files -tb ./src/tb.cpp -cflags "-I./include -I./external/community_scale_bias_hls/include"
open_solution -reset sol1
set_part xck26-sfvc784-2LV-c
create_clock -period 5.0 -name default
csim_design
csynth_design
export_design -format ip_catalog -vendor fpgai -version 1.0
exit
