from __future__ import annotations


def emit_csim_tcl(
    *,
    top_name: str = "deeplearn",
    part: str,
    clk_period_ns: float = 5.0,
    input_bin_path: str,
    weights_mode: str = "embedded",
) -> str:
    if weights_mode in ("stream", "ddr"):
        weight_src_line = 'add_files ${SRC_DIR}/weights_runtime.cpp -cflags "-I${INC_DIR} -I${LAYERS_INC_DIR}"'
    else:
        weight_src_line = 'add_files ${SRC_DIR}/fpgai_params.cpp -cflags "-I${INC_DIR} -I${LAYERS_INC_DIR}"'

    return f"""\
# Auto-generated by fpgai
open_project -reset fpgai_hls_proj
set_top {top_name}

set SRC_DIR ./src
set INC_DIR ./include
set LAYERS_INC_DIR ./include/layers

# Design sources
if {{[file exists "${{SRC_DIR}}/{top_name}.cpp"]}} {{
    add_files ${{SRC_DIR}}/{top_name}.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}} else {{
    add_files ${{SRC_DIR}}/deeplearn.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}

{weight_src_line}

if {{[file exists "${{SRC_DIR}}/layers/dense.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/dense.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}
if {{[file exists "${{SRC_DIR}}/layers/conv.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/conv.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}
if {{[file exists "${{SRC_DIR}}/layers/pool.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/pool.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}
if {{[file exists "${{SRC_DIR}}/layers/activations.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/activations.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}
if {{[file exists "${{SRC_DIR}}/layers/model_inst.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/model_inst.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"
}}

# Testbench
add_files -tb ${{SRC_DIR}}/tb.cpp -cflags "-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}"

open_solution -reset sol1
set_part {part}
create_clock -period {clk_period_ns} -name default

# 1. C Simulation
csim_design -argv "{input_bin_path}"

# 2. C Synthesis
csynth_design

# 3. Export IP
export_design -format ip_catalog -description "FPGAI Neural Network" -vendor "fpgai" -version "1.0"

exit
"""