from __future__ import annotations


def emit_csim_tcl(
    *,
    top_name: str = "deeplearn",
    part: str,
    clk_period_ns: float = 5.0,
    input_bin_path: str,
    weights_mode: str = "embedded",
    intermediate_dump: bool = False,
) -> str:
    normalized_weights_mode = str(weights_mode).strip().lower()
    extra_cflags = ""
    if intermediate_dump:
        extra_cflags += " -DFPGAI_DEBUG_DUMP"

    top_cflags = f'-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}{extra_cflags}'
    tb_cflags = f'-I${{INC_DIR}} -I${{LAYERS_INC_DIR}}{extra_cflags}'

    runtime_weight_lines = []
    if normalized_weights_mode in {"stream", "streamed", "ddr", "dma_ddr"}:
        runtime_weight_lines.append(
            'if {[file exists "${SRC_DIR}/weights_runtime.cpp"]} {'
        )
        runtime_weight_lines.append(
            f'    add_files ${{SRC_DIR}}/weights_runtime.cpp -cflags "{top_cflags}"'
        )
        runtime_weight_lines.append('}')

    runtime_weight_lines.append(
        'if {[file exists "${SRC_DIR}/fpgai_params.cpp"]} {'
    )
    runtime_weight_lines.append(
        f'    add_files ${{SRC_DIR}}/fpgai_params.cpp -cflags "{top_cflags}"'
    )
    runtime_weight_lines.append('}')
    weight_src_lines = "\n".join(runtime_weight_lines)

    return f"""\
# Auto-generated by fpgai
open_project -reset fpgai_hls_proj
set_top {top_name}

set SRC_DIR ./src
set INC_DIR ./include
set LAYERS_INC_DIR ./include/layers

if {{[file exists "${{SRC_DIR}}/{top_name}.cpp"]}} {{
    add_files ${{SRC_DIR}}/{top_name}.cpp -cflags "{top_cflags}"
}} else {{
    add_files ${{SRC_DIR}}/deeplearn.cpp -cflags "{top_cflags}"
}}

{weight_src_lines}

if {{[file exists "${{SRC_DIR}}/layers/dense.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/dense.cpp -cflags "{top_cflags}"
}}
if {{[file exists "${{SRC_DIR}}/layers/conv.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/conv.cpp -cflags "{top_cflags}"
}}
if {{[file exists "${{SRC_DIR}}/layers/pool.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/pool.cpp -cflags "{top_cflags}"
}}
if {{[file exists "${{SRC_DIR}}/layers/activations.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/activations.cpp -cflags "{top_cflags}"
}}
if {{[file exists "${{SRC_DIR}}/layers/batchnorm.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/batchnorm.cpp -cflags "{top_cflags}"
}}
if {{[file exists "${{SRC_DIR}}/layers/model_inst.cpp"]}} {{
    add_files ${{SRC_DIR}}/layers/model_inst.cpp -cflags "{top_cflags}"
}}

add_files -tb ${{SRC_DIR}}/tb.cpp -cflags "{tb_cflags}"

open_solution -reset sol1
set_part {part}
create_clock -period {clk_period_ns} -name default

csim_design -argv "{input_bin_path}"
csynth_design
export_design -format ip_catalog -description "FPGAI Neural Network" -vendor "fpgai" -version "1.0"

exit
"""
