"""Generate the board-side runtime adapter included in a package."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

def _emit_board_runtime_backend(package_dir: Path, payload: Mapping[str, Any]) -> dict[str, Any]:
    """Emit a generated board-runtime adapter for PYNQ/KV260-style backends.

    The adapter wraps a real board object, drives generated HLS mode numbers, and
    can allocate/synchronise PYNQ buffers from the generated buffer_plan.json.
    """
    backend_path = package_dir / "board_runtime.py"
    backend_path.write_text(
        "\n".join(
            [
                '"""FPGAI generated board-runtime adapter.\n\nThis module maps runtime commands to generated HLS mode numbers and allocates\nPYNQ/KV260 buffers from buffer_plan.json. It does not fake hardware execution:\nwithout a real Overlay/IP or explicit fake object in tests, board calls fail.\n"""',
                "from __future__ import annotations",
                "",
                "import json",
                "from pathlib import Path",
                "from typing import Any",
                "",
                "FPGAI_MODE_RUN_INFERENCE = 0",
                "FPGAI_MODE_EXPORT_WEIGHTS = 2",
                "FPGAI_MODE_RUN_TRAINING = 2",
                "FPGAI_MODE_ACCUMULATE_GRADIENTS = 3",
                "FPGAI_MODE_APPLY_ACCUMULATED_GRADIENTS = 4",
                "FPGAI_MODE_RESET_ACCUMULATORS = 5",
                "FPGAI_MODE_EXPORT_GRADIENTS = 8",
                "FPGAI_MODE_EXPORT_OPTIMIZER_STATE = 9",
                "",
                "def load_buffer_plan(package_dir: str | Path | None = None) -> dict[str, Any]:",
                "    base = Path(package_dir) if package_dir is not None else Path(__file__).resolve().parent",
                "    path = base / 'buffer_plan.json'",
                "    if not path.exists():",
                "        return {'buffers': []}",
                "    return json.loads(path.read_text(encoding='utf-8'))",
                "",
                "def _numpy_dtype(dtype: str) -> Any:",
                "    import numpy as np  # imported lazily so runtime_api imports without numpy when unused",
                "    mapping = {'float32': np.float32, 'float': np.float32, 'uint32': np.uint32, 'int32': np.int32}",
                "    return mapping.get(str(dtype).lower(), np.float32)",
                "",
                "def allocate_buffers_from_plan(buffer_plan: dict[str, Any] | None = None, *, allocate_fn: Any | None = None, package_dir: str | Path | None = None) -> dict[str, Any]:",
                "    base = Path(package_dir) if package_dir is not None else Path(__file__).resolve().parent",
                "    plan = buffer_plan or load_buffer_plan(base)",
                "    if allocate_fn is None:",
                "        try:",
                "            from pynq import allocate as allocate_fn  # type: ignore",
                "        except Exception as exc:",
                "            raise RuntimeError('PYNQ allocate() is not available; pass allocate_fn=... in tests or run on the target board.') from exc",
                "    buffers: dict[str, Any] = {}",
                "    for entry in plan.get('buffers', []):",
                "        name = str(entry['name'])",
                "        shape = tuple(int(v) for v in entry.get('shape', [int(entry.get('words', 1))]))",
                "        dtype = _numpy_dtype(str(entry.get('dtype', 'float32')))",
                "        buf = allocate_fn(shape=shape, dtype=dtype)",
                "        source = entry.get('source')",
                "        if source:",
                "            source_path = base / str(source)",
                "            if source_path.exists() and source_path.is_file():",
                "                payload = source_path.read_bytes()",
                "                try:",
                "                    import numpy as np",
                "                    values = np.frombuffer(payload, dtype=dtype)",
                "                    flat = buf.reshape(-1) if hasattr(buf, 'reshape') else buf",
                "                    count = min(len(flat), len(values))",
                "                    flat[:count] = values[:count]",
                "                except Exception as exc:",
                "                    raise RuntimeError(f'Failed to preload runtime buffer {name!r} from {source_path}: {exc}') from exc",
                "        buffers[name] = buf",
                "    return buffers",
                "",
                "def _sync_to_device(buf: Any) -> None:",
                "    if hasattr(buf, 'sync_to_device'):",
                "        buf.sync_to_device()",
                "    elif hasattr(buf, 'flush'):",
                "        buf.flush()",
                "",
                "def _sync_from_device(buf: Any) -> None:",
                "    if hasattr(buf, 'sync_from_device'):",
                "        buf.sync_from_device()",
                "    elif hasattr(buf, 'invalidate'):",
                "        buf.invalidate()",
                "",
                "def sync_buffers(buffers: dict[str, Any], names: list[str], *, direction: str) -> None:",
                "    for name in names:",
                "        if name not in buffers:",
                "            raise RuntimeError(f'Runtime buffer {name!r} is required by the execution plan but is not allocated/bound.')",
                "        if direction == 'to_device':",
                "            _sync_to_device(buffers[name])",
                "        elif direction == 'from_device':",
                "            _sync_from_device(buffers[name])",
                "        else:",
                "            raise ValueError(f'Unsupported buffer sync direction: {direction}')",
                "",
                "class PynqDmaMmioBackend:",
                "    \"\"\"Concrete PYNQ/KV260-style backend for generated FPGAI runtime packages.\"\"\"",
                "    def __init__(self, *, bitfile: str | Path | None = None, overlay: Any | None = None, ip_name: str | None = None, dma_name: str | None = None, buffers: dict[str, Any] | None = None, mode_offset: int = 0x10, ap_ctrl_offset: int = 0x00, start_mask: int = 0x01, done_mask: int = 0x02, timeout_cycles: int = 1000000):",
                "        self.mode_offset = int(mode_offset)",
                "        self.ap_ctrl_offset = int(ap_ctrl_offset)",
                "        self.start_mask = int(start_mask)",
                "        self.done_mask = int(done_mask)",
                "        self.timeout_cycles = int(timeout_cycles)",
                "        self.buffers = dict(buffers or {})",
                "        if overlay is None:",
                "            if bitfile is None:",
                "                raise ValueError('PynqDmaMmioBackend requires either overlay=... or bitfile=...')",
                "            try:",
                "                from pynq import Overlay  # type: ignore",
                "            except Exception as exc:",
                "                raise RuntimeError('PYNQ is not available; install/use this backend on the target board.') from exc",
                "            overlay = Overlay(str(bitfile))",
                "        self.overlay = overlay",
                "        self.ip = self._resolve_ip(ip_name)",
                "        self.dma = self._resolve_dma(dma_name)",
                "",
                "    def _resolve_ip(self, ip_name: str | None) -> Any:",
                "        names: list[str] = []",
                "        if ip_name:",
                "            names.append(ip_name)",
                "        names.extend(['deeplearn_0', 'deeplearn', 'deeplearn_top_0'])",
                "        for name in names:",
                "            if hasattr(self.overlay, name):",
                "                return getattr(self.overlay, name)",
                "        ip_dict = getattr(self.overlay, 'ip_dict', {}) or {}",
                "        for name in names:",
                "            if name in ip_dict and hasattr(self.overlay, name):",
                "                return getattr(self.overlay, name)",
                "        if hasattr(self.overlay, 'write') and hasattr(self.overlay, 'read'):",
                "            return self.overlay",
                "        raise RuntimeError(f'Could not resolve generated HLS IP. Tried: {names}')",
                "",
                "    def _resolve_dma(self, dma_name: str | None) -> Any | None:",
                "        names: list[str] = []",
                "        if dma_name:",
                "            names.append(dma_name)",
                "        names.extend(['axi_dma_0', 'dma', 'axi_dma'])",
                "        for name in names:",
                "            if hasattr(self.overlay, name):",
                "                return getattr(self.overlay, name)",
                "        return None",
                "",
                "    def _wait_done(self) -> None:",
                "        for _ in range(max(1, self.timeout_cycles)):",
                "            status = int(self.ip.read(self.ap_ctrl_offset))",
                "            if status & self.done_mask:",
                "                return",
                "        raise TimeoutError('Timed out waiting for generated HLS IP to finish.')",
                "",
                "    def _buffer_address(self, buffer: Any) -> int:",
                "        for attr in ('device_address', 'physical_address'):",
                "            value = getattr(buffer, attr, None)",
                "            if value is not None:",
                "                return int(value)",
                "        raise RuntimeError('A bound m_axi buffer does not expose device_address/physical_address.')",
                "",
                "    def _bind_pointer_register(self, logical_name: str, buffer: Any) -> bool:",
                "        register_map = getattr(self.ip, 'register_map', None)",
                "        if register_map is None:",
                "            return False",
                "        aliases = {",
                "            'input': ['input', 'in', 'input_0'],",
                "            'output': ['output', 'out', 'output_0'],",
                "            'labels': ['labels', 'label', 'targets', 'target'],",
                "            'weights': ['weights', 'weights_mem', 'weight_mem'],",
                "            'gradients_mem': ['gradients_mem', 'gradients', 'gradient_mem'],",
                "            'optimizer_state_mem': ['optimizer_state_mem', 'optimizer_state'],",
                "        }",
                "        address = self._buffer_address(buffer)",
                "        for name in aliases.get(str(logical_name), [str(logical_name)]):",
                "            if hasattr(register_map, name):",
                "                setattr(register_map, name, address)",
                "                return True",
                "        return False",
                "",
                "    def _bind_pointer_registers(self) -> None:",
                "        for name, buffer in self.buffers.items():",
                "            try:",
                "                self._bind_pointer_register(name, buffer)",
                "            except RuntimeError:",
                "                continue",
                "",
                "    def call_mode(self, mode: int, **kwargs: Any) -> Any:",
                "        self._bind_pointer_registers()",
                "        self.ip.write(self.mode_offset, int(mode))",
                "        if kwargs.get('input_buffer') is not None and self.dma is not None:",
                "            self.dma.sendchannel.transfer(kwargs['input_buffer'])",
                "        if self.dma is not None and kwargs.get('output_buffer') is not None:",
                "            self.dma.recvchannel.transfer(kwargs['output_buffer'])",
                "        self.ip.write(self.ap_ctrl_offset, self.start_mask)",
                "        if self.dma is not None and kwargs.get('output_buffer') is not None:",
                "            self.dma.sendchannel.wait()",
                "            self.dma.recvchannel.wait()",
                "        else:",
                "            self._wait_done()",
                "        return {'mode': int(mode)}",
                "",
                "    def bind_buffer(self, logical_name: str, buffer: Any) -> None:",
                "        self.buffers[str(logical_name)] = buffer",
                "",
                "    def bind_buffers(self, buffers: dict[str, Any]) -> None:",
                "        for name, buf in dict(buffers).items():",
                "            self.bind_buffer(str(name), buf)",
                "",
                "    def read_buffer(self, logical_name: str) -> bytes:",
                "        if logical_name not in self.buffers:",
                "            raise RuntimeError(f'No board buffer bound for {logical_name!r}.')",
                "        buf = self.buffers[logical_name]",
                "        _sync_from_device(buf)",
                "        if isinstance(buf, (bytes, bytearray, memoryview)):",
                "            return bytes(buf)",
                "        if hasattr(buf, 'tobytes'):",
                "            return bytes(buf.tobytes())",
                "        try:",
                "            return memoryview(buf).tobytes()",
                "        except TypeError as exc:",
                "            raise TypeError(f'Buffer {logical_name!r} cannot be converted to bytes.') from exc",
                "",
                "    def run_inference(self, inputs: Any | None = None, *, repeat: int = 1) -> Any:",
                "        result = None",
                "        for _ in range(int(repeat)):",
                "            result = self.call_mode(FPGAI_MODE_RUN_INFERENCE, inputs=inputs, input_buffer=self.buffers.get('input'), output_buffer=self.buffers.get('output'))",
                "        return result",
                "",
                "    def run_training(self, inputs: Any | None = None, labels: Any | None = None, *, steps: int = 1) -> Any:",
                "        result = None",
                "        for _ in range(int(steps)):",
                "            result = self.call_mode(FPGAI_MODE_RUN_TRAINING, inputs=inputs, labels=labels, input_buffer=self.buffers.get('input'), labels_buffer=self.buffers.get('labels'), output_buffer=self.buffers.get('output'))",
                "        return result",
                "",
                "    def reset_accumulators(self) -> Any:",
                "        return self.call_mode(FPGAI_MODE_RESET_ACCUMULATORS)",
                "",
                "    def accumulate_gradients(self, inputs: Any | None = None, labels: Any | None = None, *, steps: int = 1) -> Any:",
                "        result = None",
                "        for _ in range(int(steps)):",
                "            result = self.call_mode(FPGAI_MODE_ACCUMULATE_GRADIENTS, inputs=inputs, labels=labels, input_buffer=self.buffers.get('input'))",
                "        return result",
                "",
                "    def apply_accumulated_gradients(self) -> Any:",
                "        return self.call_mode(FPGAI_MODE_APPLY_ACCUMULATED_GRADIENTS)",
                "",
                "    def export_weights(self) -> bytes:",
                "        self.call_mode(FPGAI_MODE_EXPORT_WEIGHTS, output_buffer=self.buffers.get('weights'))",
                "        return self.read_buffer('weights')",
                "",
                "    def export_gradients(self) -> bytes:",
                "        self.call_mode(FPGAI_MODE_EXPORT_GRADIENTS, output_buffer=self.buffers.get('gradients_mem'))",
                "        return self.read_buffer('gradients_mem')",
                "",
                "    def export_optimizer_state(self) -> bytes:",
                "        self.call_mode(FPGAI_MODE_EXPORT_OPTIMIZER_STATE, output_buffer=self.buffers.get('optimizer_state_mem'))",
                "        return self.read_buffer('optimizer_state_mem')",
                "",
                "def create_pynq_backend(*, bitfile: str | Path | None = None, overlay: Any | None = None, ip_name: str | None = None, dma_name: str | None = None, buffers: dict[str, Any] | None = None, mode_offset: int = 0x10, buffer_plan: dict[str, Any] | None = None, allocate_fn: Any | None = None) -> PynqDmaMmioBackend:",
                "    allocated = allocate_buffers_from_plan(buffer_plan, allocate_fn=allocate_fn) if buffer_plan is not None or allocate_fn is not None else {}",
                "    allocated.update(dict(buffers or {}))",
                "    return PynqDmaMmioBackend(bitfile=bitfile, overlay=overlay, ip_name=ip_name, dma_name=dma_name, buffers=allocated, mode_offset=mode_offset)",
                "",
                "class FPGAIBoardRuntime:",
                "    def __init__(self, backend: Any, *, package_dir: str | Path | None = None, buffers: dict[str, Any] | None = None):",
                "        if backend is None:",
                "            raise ValueError('FPGAIBoardRuntime requires a real backend object.')",
                "        self.backend = backend",
                "        self.package_dir = Path(package_dir) if package_dir is not None else Path(__file__).resolve().parent",
                "        self.buffers = dict(buffers or getattr(backend, 'buffers', {}) or {})",
                "        if self.buffers and hasattr(self.backend, 'bind_buffers'):",
                "            self.backend.bind_buffers(self.buffers)",
                "",
                "    def bind_buffers(self, buffers: dict[str, Any]) -> None:",
                "        self.buffers.update(dict(buffers))",
                "        if hasattr(self.backend, 'bind_buffers'):",
                "            self.backend.bind_buffers(buffers)",
                "        elif hasattr(self.backend, 'bind_buffer'):",
                "            for name, buf in dict(buffers).items():",
                "                self.backend.bind_buffer(name, buf)",
                "",
                "    def sync_before(self, names: list[str]) -> None:",
                "        sync_buffers(self.buffers, names, direction='to_device')",
                "",
                "    def sync_after(self, names: list[str]) -> None:",
                "        sync_buffers(self.buffers, names, direction='from_device')",
                "",
                "    def _call_mode(self, mode: int, **kwargs: Any) -> Any:",
                "        if hasattr(self.backend, 'call_mode'):",
                "            return self.backend.call_mode(mode, **kwargs)",
                "        if hasattr(self.backend, 'set_mode'):",
                "            self.backend.set_mode(mode)",
                "            if hasattr(self.backend, 'run'):",
                "                return self.backend.run(**kwargs)",
                "        raise RuntimeError('Backend must implement call_mode(mode, **kwargs) or set_mode(mode)+run().')",
                "",
                "    def _read_payload(self, logical_name: str, fallback_method: str | None = None) -> bytes:",
                "        if fallback_method and hasattr(self.backend, fallback_method):",
                "            payload = getattr(self.backend, fallback_method)()",
                "        elif hasattr(self.backend, 'read_buffer'):",
                "            payload = self.backend.read_buffer(logical_name)",
                "        elif hasattr(self.backend, 'read_m_axi'):",
                "            payload = self.backend.read_m_axi(logical_name)",
                "        elif logical_name in self.buffers:",
                "            buf = self.buffers[logical_name]",
                "            _sync_from_device(buf)",
                "            payload = buf.tobytes() if hasattr(buf, 'tobytes') else memoryview(buf).tobytes()",
                "        else:",
                "            raise RuntimeError(f'Backend cannot read exported payload {logical_name!r}.')",
                "        if not isinstance(payload, (bytes, bytearray, memoryview)):",
                "            raise TypeError(f'Backend returned non-bytes payload for {logical_name!r}.')",
                "        return bytes(payload)",
                "",
                "    def _write_capture(self, payload: bytes, default_relpath: str, capture_path: str | Path | None) -> Path:",
                "        target = Path(capture_path) if capture_path is not None else self.package_dir / default_relpath",
                "        target.parent.mkdir(parents=True, exist_ok=True)",
                "        target.write_bytes(payload)",
                "        return target",
                "",
                "    def run_inference(self, inputs: Any | None = None, *, repeat: int = 1) -> Any:",
                "        if int(repeat) < 1:",
                "            raise ValueError('repeat must be >= 1')",
                "        if hasattr(self.backend, 'run_inference'):",
                "            return self.backend.run_inference(inputs=inputs, repeat=int(repeat))",
                "        result = None",
                "        for _ in range(int(repeat)):",
                "            result = self._call_mode(FPGAI_MODE_RUN_INFERENCE, inputs=inputs, input_buffer=self.buffers.get('input'), output_buffer=self.buffers.get('output'))",
                "        return result",
                "",
                "    def export_weights(self, *, capture_path: str | Path | None = None) -> bytes:",
                "        if hasattr(self.backend, 'export_weights'):",
                "            payload = self.backend.export_weights()",
                "        else:",
                "            self._call_mode(FPGAI_MODE_EXPORT_WEIGHTS, output_buffer=self.buffers.get('weights'))",
                "            payload = self._read_payload('weights', 'read_weights')",
                "        payload = bytes(payload)",
                "        self._write_capture(payload, 'outputs/weights_after.bin', capture_path)",
                "        return payload",
                "",
                "    def run_training(self, inputs: Any | None = None, labels: Any | None = None, *, steps: int = 1) -> Any:",
                "        if int(steps) < 1:",
                "            raise ValueError('steps must be >= 1')",
                "        if hasattr(self.backend, 'run_training'):",
                "            return self.backend.run_training(inputs=inputs, labels=labels, steps=int(steps))",
                "        result = None",
                "        for _ in range(int(steps)):",
                "            result = self._call_mode(FPGAI_MODE_RUN_TRAINING, inputs=inputs, labels=labels, input_buffer=self.buffers.get('input'), output_buffer=self.buffers.get('output'))",
                "        return result",
                "",
                "    def reset_accumulators(self) -> Any:",
                "        if hasattr(self.backend, 'reset_accumulators'):",
                "            return self.backend.reset_accumulators()",
                "        return self._call_mode(FPGAI_MODE_RESET_ACCUMULATORS)",
                "",
                "    def accumulate_gradients(self, inputs: Any | None = None, labels: Any | None = None, *, steps: int = 1) -> Any:",
                "        if int(steps) < 1:",
                "            raise ValueError('steps must be >= 1')",
                "        result = None",
                "        for _ in range(int(steps)):",
                "            if hasattr(self.backend, 'accumulate_gradients'):",
                "                result = self.backend.accumulate_gradients(inputs=inputs, labels=labels, steps=1)",
                "            else:",
                "                result = self._call_mode(FPGAI_MODE_ACCUMULATE_GRADIENTS, inputs=inputs, labels=labels, input_buffer=self.buffers.get('input'))",
                "        return result",
                "",
                "    def apply_accumulated_gradients(self) -> Any:",
                "        if hasattr(self.backend, 'apply_accumulated_gradients'):",
                "            return self.backend.apply_accumulated_gradients()",
                "        return self._call_mode(FPGAI_MODE_APPLY_ACCUMULATED_GRADIENTS)",
                "",
                "    def export_gradients(self, *, capture_path: str | Path | None = None) -> bytes:",
                "        if hasattr(self.backend, 'export_gradients'):",
                "            payload = self.backend.export_gradients()",
                "        else:",
                "            self._call_mode(FPGAI_MODE_EXPORT_GRADIENTS)",
                "            payload = self._read_payload('gradients_mem', 'read_gradients')",
                "        payload = bytes(payload)",
                "        self._write_capture(payload, 'outputs/gradients_after.bin', capture_path)",
                "        return payload",
                "",
                "    def export_optimizer_state(self, *, capture_path: str | Path | None = None) -> bytes:",
                "        if hasattr(self.backend, 'export_optimizer_state'):",
                "            payload = self.backend.export_optimizer_state()",
                "        else:",
                "            self._call_mode(FPGAI_MODE_EXPORT_OPTIMIZER_STATE)",
                "            payload = self._read_payload('optimizer_state_mem', 'read_optimizer_state')",
                "        payload = bytes(payload)",
                "        self._write_capture(payload, 'outputs/optimizer_state_after.bin', capture_path)",
                "        return payload",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return {"source": backend_path.as_posix(), "package_path": "board_runtime.py", "bytes": backend_path.stat().st_size, "present": True}
